
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kindergarten_exchange_development

test:
  <<: *default
  database: kindergarten_exchange_test

production:
  <<: *default
  database: kindergarten_exchange_production
  username: kindergarten_exchange
  password: <%= ENV["KINDERGARTEN_EXCHANGE_DATABASE_PASSWORD"] %>
