name: Rails
on: pull_request

jobs:
  verify:
    name: Build
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: rails_github_actions
          POSTGRES_DB: rails_github_actions_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # if you need redis
      # redis:
      #   image: redis
      #   ports:
      #   - 6379:6379
      #   options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.18.0
      - name: Install dependencies
        run: |
        
          gem install bundler
          bundle install
          yarn install
      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DB: kindergarten_exchange_test
          
        run: |
          cp config/database.yml config/database.yml
          rake db:create db:migrate
      - name: Run tests
        env:
          PGHOST: localhost
          POSTGRES_DB: kindergarten_exchange_test
      
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: rspec